spring:
  application:
    name: stock
#  datasource:
#    url: jdbc:postgresql://localhost:5432/stock
#    username: develop
#    password: password
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
      show-sql: true
  docker:
    compose:
      enabled: true
      file: compose-dev.yml